// Writes word-font.js: Patrick Hand as a data URL (a file:// font could fail to load
// in the renderer, and anything file:// near the canvas risks tainting it).
// Run once, or again if public/fonts/patrick-hand.woff2 changes:  node make-font.mjs
import { readFileSync, writeFileSync } from 'node:fs';
const b64 = readFileSync(new URL('../public/fonts/patrick-hand.woff2', import.meta.url)).toString('base64');
writeFileSync(new URL('./word-font.js', import.meta.url),
`// Generated by make-font.mjs from public/fonts/patrick-hand.woff2 (SIL Open Font License). Don't edit.
const PATRICK_HAND_URL = 'data:font/woff2;base64,${b64}';
const FONT_READY = (async () => { const f = new FontFace('Patrick Hand', 'url(' + PATRICK_HAND_URL + ')'); await f.load(); document.fonts.add(f); })();
`);
console.log('word-font.js written, ' + b64.length + ' base64 chars');
