# Recolours the user's logos (video/public/adtn/logo-*.png, white for dark backgrounds)
# for white paper, and embeds them as data URLs: a canvas that draws a file:// image
# is tainted and can't export frames. Run: python prep-logos.py
from PIL import Image
import base64, io
INK = (0x1b, 0x23, 0x40); BLUE = (0x2f, 0x6b, 0xff); GRN = (0x14, 0x9a, 0x4f)
def enc(im):
    b = io.BytesIO(); im.save(b, 'PNG', optimize=True); return 'data:image/png;base64,' + base64.b64encode(b.getvalue()).decode()
def prep(path, width, colour):
    im = Image.open(path).convert('RGBA'); h = round(im.height * width / im.width); im = im.resize((width, h), Image.LANCZOS)
    px = im.load(); col = Image.new('RGBA', im.size); cp = col.load(); sil = Image.new('RGBA', im.size); sp = sil.load()
    for y in range(im.height):
        for x in range(im.width):
            r, g, b, a = px[x, y]
            if a == 0: continue
            cp[x, y] = colour(r, g, b) + (a,); sp[x, y] = (0, 0, 0, a)
    return enc(col), enc(sil), im.size
# Astral: the white PROJECT.IN (and where the slate ASTRAL overlaps it, ~150) -> ink; the slate ASTRAL (~85) -> bright blue
astral = prep('../video/public/adtn/logo-astral.png', 1000, lambda r, g, b: INK if (r + g + b) / 3 > 125 else BLUE)
greenr = prep('../video/public/adtn/logo-greenr.png', 800, lambda r, g, b: GRN)
with open('logos.js', 'w') as f:
    f.write("// Generated by prep-logos.py from video/public/adtn/logo-*.png (the user's logos), recoloured for white paper.\n")
    for name, (c, s, size) in (('astral', astral), ('greenr', greenr)):
        f.write(f"const LOGO_{name.upper()} = {{ w: {size[0]}, h: {size[1]}, src: '{c}', sil: '{s}' }};\n")
