/**
 * transcribe.mjs — word-level timings for the reel's voiceover.
 *
 *   node scripts/reel/transcribe.mjs <instance> [path/to/vo.mp3]   transcribe
 *   node scripts/reel/transcribe.mjs <instance> --from-json          rebuild voWords.ts only
 *
 * A path given is copied to public/<assets>/vo.<ext> first, so the VO the
 * reel plays is always the VO that was transcribed.
 *
 * whisper.cpp + the small.en model install into WHISPER_DIR (default
 * ~/.cache/remotion-whisper, outside the repo; ~0.5GB on first run) via
 * @remotion/install-whisper-cpp. Writes:
 *
 *   public/<assets>/vo-words.json   raw Remotion Caption[] tokens, for reference
 *   <instance>/voWords.ts           WORDS { w, s, e } in seconds + GAPS (silences)
 *
 * WHY THE SNAP: whisper starts a phrase's first word at the END of the pause
 * before it — 0.2–0.4s early ("Come" at 2.24s, spoken at 2.45s). Every word
 * that begins inside a detected silence is moved to where the speech resumes,
 * and every word that ends inside one is clipped to where it began. Later
 * words in a phrase are accurate; phrase starts are where cuts and caption
 * changes sit, so this matters.
 */

import { copyFileSync, existsSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import { extname, join, resolve } from "node:path";
import { die, ensureDir, ff, ffLog, findVo, loadInstance } from "./lib.mjs";

const inst = await loadInstance(process.argv[2]);
const fromJson = process.argv.includes("--from-json");
const given = process.argv[3] && !process.argv[3].startsWith("--") ? resolve(process.argv[3]) : null;
ensureDir(inst.pub);
if (given) {
  if (!existsSync(given)) die(`no such file: ${given}`);
  const dest = join(inst.pub, `vo${extname(given).toLowerCase() || ".mp3"}`);
  if (resolve(dest) !== given) copyFileSync(given, dest);
  console.log(`VO -> ${dest}`);
}
const vo = findVo(inst.pub);
if (!vo) die(`no vo.mp3 / vo.wav / vo.m4a in ${inst.pub} — pass the voiceover file as the second argument`);
const JSON_OUT = join(inst.pub, "vo-words.json");
const TS_OUT = inst.file("voWords.ts");

if (!fromJson) {
  const { downloadWhisperModel, installWhisperCpp, transcribe, toCaptions } = await import("@remotion/install-whisper-cpp");
  const to = process.env.WHISPER_DIR ?? join(os.homedir(), ".cache", "remotion-whisper");
  const MODEL = "small.en";
  const VERSION = "1.5.5";
  await installWhisperCpp({ to, version: VERSION });
  await downloadWhisperModel({ model: MODEL, folder: to });
  const wav = join(os.tmpdir(), `reel-vo-16k-${process.pid}.wav`);
  ff(["-i", vo, "-ar", "16000", "-ac", "1", wav]);
  const whisperCppOutput = await transcribe({ model: MODEL, whisperPath: to, whisperCppVersion: VERSION, inputPath: wav, tokenLevelTimestamps: true });
  const { captions } = toCaptions({ whisperCppOutput });
  writeFileSync(JSON_OUT, JSON.stringify(captions, null, 2));
}

// Merge sub-word tokens ("B"+"ored", "It"+"'s") into words; drop punctuation-only tokens.
const tokens = JSON.parse(readFileSync(JSON_OUT, "utf8"));
const words = [];
for (const t of tokens) {
  const clean = t.text.trim();
  if (!clean || !/[A-Za-z0-9]/.test(clean)) continue;
  if (words.length === 0 || /^\s/.test(t.text)) words.push({ w: clean, s: t.startMs / 1000, e: t.endMs / 1000 });
  else {
    const last = words[words.length - 1];
    last.w += clean;
    last.e = t.endMs / 1000;
  }
}

// Snap to the real speech onsets.
const log = ffLog(["-i", vo, "-af", "silencedetect=noise=-35dB:d=0.1", "-f", "null", "-"]);
const starts = [...log.matchAll(/silence_start: ([0-9.]+)/g)].map((m) => +m[1]);
const ends = [...log.matchAll(/silence_end: ([0-9.]+)/g)].map((m) => +m[1]);
const gaps = starts.map((a, i) => [a, ends[i] ?? Infinity]);
for (const x of words) {
  for (const [a, b] of gaps) {
    if (x.s >= a - 0.02 && x.s < b) x.s = b;
    if (x.e > a && x.e <= b + 0.02) x.e = a;
  }
}

const body = words.map((x) => `  { w: ${JSON.stringify(x.w)}, s: ${x.s.toFixed(2)}, e: ${x.e.toFixed(2)} },`).join("\n");
const gapList = gaps.filter(([, b]) => Number.isFinite(b)).map(([a, b]) => `[${a.toFixed(3)}, ${b.toFixed(3)}]`).join(", ");
writeFileSync(
  TS_OUT,
  `/**\n * voWords.ts — GENERATED by scripts/reel/transcribe.mjs from public/${inst.REEL.assets}/${vo.split(/[\\/]/).pop()}. Do not edit.\n *\n * Every spoken word with its start and end in seconds, and the silences\n * between phrases. ./timeline.ts is timed from these.\n */\n\nexport const WORDS: { w: string; s: number; e: number }[] = [\n${body}\n];\n\n/** Silences in the VO, [start, end] in seconds: where phrases stop and resume. */\nexport const GAPS: [number, number][] = [${gapList}];\n`,
);
console.log(`wrote ${TS_OUT} — ${words.length} words, VO ${words.length ? words[words.length - 1].e.toFixed(2) : 0}s`);
console.log(words.map((x) => `${x.s.toFixed(2)} ${x.w}`).join(" | "));
